version: '3'
services:
  app:
    build: .
    volumes:
      - ./app:/app
    links:
      - db
    tty: true
    # command: ["node", "index.js"]
    ports:
      - 3000:3000
  db:
    image: mongo:3.4
    restart: always
    volumes:
      - ./mongodb/data:/data/db

  aggregator:
    build: ./fluentd/aggregator
    volumes:
      - ./fluentd/aggregator/fluentd:/fluentd/etc
    links:
      - db
    environment:
      FLUENTD_CONF: fluent.conf
    ports:
      - 24224:24224
  test1:
    build: ./fluentd/test1
    volumes:
      - ./fluentd/test1/fluentd:/fluentd/etc
      - ./sample/rails1/log:/tmp/log1
    environment:
      FLUENTD_CONF: fluent.conf
    ports:
      - 24225:24224
  test2:
    build: ./fluentd/test2
    volumes:
      - ./fluentd/test2/fluentd:/fluentd/etc
      - ./sample/rails2/log:/tmp/log2
    environment:
      FLUENTD_CONF: fluent.conf
    ports:
      - 24226:24224
  rails1:
    build: ./sample/rails1
    volumes:
      - ./sample/rails1:/app
      - ./sample/rails1/log:/app/log
    ports:
      - 9292:9292
    command: ["rails", "server", "-b", "0.0.0.0"]
  rails2:
    build: ./sample/rails2
    volumes:
      - ./sample/rails2:/app
      - ./sample/rails2/log:/app/log
    ports:
      - 9293:9292
    command: ["rails", "server", "-b", "0.0.0.0"]
#    tty: true
#    depends_on:
#      - aggregator
#    logging:
#      driver: fluentd
#      options:
#        fluentd-address: localhost:24226
#        tag: remotetail.{{.ID}}-{{.Name}}